import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Remarkable',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Remarkable',
    siteName: 'WB API',
    url: 'https://remarkable-alpha.vercel.app/',
    description: 'Remarkable site',
    //type: type,
    //locale: locale,
    //images: imgSrc
  }

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
